# Generated by Django 5.1 on 2024-08-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usarios',
            new_name='Usuario',
        ),
    ]
